<?xml version="1.0"?>
<sdf version="1.7" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.14159" />

    <xacro:property name="bob_radius" value="0.05" />
    <xacro:property name="base_radius" value="0.05" />
    <xacro:property name="arm_radius" value="0.01" />
    <xacro:property name="arm_mass" value="0.1" />
    <xacro:property name="bob_mass" value="0.5" />
    
    <xacro:property name="base_size_x" value="0.5" />
    <xacro:property name="base_size_y" value="0.5" />

    <xacro:property name="arm_holder_size_x" value="0.02" />
    <xacro:property name="arm_holder_size_y" value="0.01" />
    <xacro:property name="arm_holder_size_z" value="0.01" />
    
    <xacro:include filename="basic_sphere.xacro"/>
    <xacro:include filename="basic_box.xacro"/>
    <xacro:include filename="basic_cylinder.xacro"/>

    <xacro:macro name="simple_pendulum" params="x y z theta_0 arm_length">
        <model name="simple_pendulum">
            <pose>${x} ${y} ${z + 0.01} 0 0 0</pose>

            <link name="base_link">
                <static>true</static>
                <xacro:basic_box pos="0 0 ${-z/2}" rot="0 0 0" mass="1000"
                size_x="${base_size_x}" size_y="${base_size_y}" size_z="${z}"
                color="0 0 1 1"/>
            </link>

            <link name="arm_holder">
                <xacro:basic_box pos="${base_size_x} 0 0" rot="0 0 0" mass="0.1"
                size_x="${arm_holder_size_x}" size_y="${arm_holder_size_y}" 
                size_z="${arm_holder_size_z}" color="0.5 0 0.5 1"/>
            </link>

            <link name="arm">
                <xacro:basic_cylinder pos="${arm_holder_size_x + base_size_x} 0 ${-arm_length/2}"
                    rot="${theta_0} 0 0" mass="0.1" radius="${arm_radius}"
                    length="${arm_length}" color="1 0 0 1"/>
            </link>

            <link name="bob">
                <xacro:basic_solid_sphere pos="${arm_holder_size_x + base_size_x} 0 ${arm_length}" rot="0 0 0"
                radius="${bob_radius}" color="0 1 0 1" mass="10"/>
            </link>

            <joint name="arm_joint" type="revolute">
                <parent>arm_holder</parent>
                <child>arm</child>
                <axis>
                    <xyz>0 1 0</xyz>
                    <limit>
                        <lower>-1e16</lower>
                        <upper>1e16</upper>
                    </limit>
                </axis>
                <pose>0 0 0 0 0 0</pose>
            </joint>

            <joint name="arm_holder_joint" type="fixed">
                <parent>base_link</parent>
                <child>arm_holder</child>
            </joint>
            <joint name="bob_joint" type="fixed">
                <parent>arm</parent>
                <child>bob</child>
            </joint>
        </model>
    </xacro:macro>
</sdf>